variable "AZ_BILLING_ACCOUNT_NAME" {
  type        = string
  description = "MAPS TO ENVIRONMENTAL VARIABLE TF_VAR_AZ_BILLING_ACCOUNT_NAME"
}

variable "AZ_BILLING_PROFILE_NAME" {
  type        = string
  description = "MAPS TO ENVIRONMENTAL VARIABLE TF_VAR_AZ_BILLING_PROFILE_NAME"
}

variable "AZ_INVOICE_SECTION_NAME" {
  type        = string
  description = "MAPS TO ENVIRONMENTAL VARIABLE TF_VAR_AZ_INVOICE_SECTION_NAME"
}